---
- hosts: 172.31.32.34
  become: yes
  tasks:
  - name: i want to execute direct command
    command: hostname -f
    register: myresult

  - name: i want to display the result
    debug:
      msg: "{{myresult}}"
   