---
- hosts: 172.31.32.34
  become: yes
  tasks:
  - name: i want to install git
    apt: 
      name: git
      state: present
  - name: i wnat to install tree
    apt: 
      name: tree
      statee: present
     ignore_errors: yes
  - name: i want to install wget
    apt:
      name: wget
      state: present