---
- hosts: 172.31.32.34
  become: yes
  tasks:
  - include_tasks: createfile.yml
  - name: i want to install webservers
    apt:
      name: "{{webserveronubuntu}}"
      state: present
  - name: i want to copy static files on node servers
    template:
      src: index.j2
      dest: /var/www/html/index.html