---
- hosts: 172.31.32.34
  become: yes
  tasks:
  - name: i want to install git
    apt: 
      name: "{{gitpack}}"
      state: present
    tags: mygit
  - name: i want to install tree
    apt: 
      name: "{{treepack}}"
      state: present
    tags: mytree
  - name: i want to install wget
    apt: 
      name: "{{wgetpack}}"
      state: present
    tags: mywget
  