---
- hosts: webservers
  become: yes
  tasks:
  - name: git tasks
    tags: mygit
    block:
    - name: i want to install git on ubuntu
      apt: 
        name: "{{gitpack}}"
        state: present
      when: ansible_os_family =="Debian"
    - name: i want to install git on RedHat
      yum: 
        name: "{{gitpack}}"
        state: present
      when: ansible_os_family =="RedHat"
    - name: i want to install tree on ubuntu
      apt: 
        name: "{{treepack}}"
        state: present
      when: ansible_os_family =="Debian"
    - name: i want to install tree on RedHat
      yum: 
        name: "{{treepack}}"
        state: present
      when: ansible_os_family =="RedHat"
  - tags: mywget
    block:
    - name: i want to install wget on ubuntu
      apt: 
        name: "{{wgetpack}}"
        state: present
      when: ansible_os_family =="Debian"
    - name: i want to install wget on RedHat
      yum: 
        name: "{{wgetpack}}"
        state: present
      when: ansible_os_family =="RedHat"
   
    
  